
CREATE EXTENSION IF NOT EXISTS vector;
CREATE TABLE IF NOT EXISTS users(id BIGSERIAL PRIMARY KEY,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL CHECK (role IN ('admin','developer','user')),created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS refresh_tokens(id BIGSERIAL PRIMARY KEY,user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,token TEXT NOT NULL,created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS projects(id SERIAL PRIMARY KEY,name TEXT NOT NULL,status TEXT DEFAULT 'active',progress NUMERIC DEFAULT 0);
CREATE TABLE IF NOT EXISTS interactions(id BIGSERIAL PRIMARY KEY,user_id TEXT,ts TIMESTAMPTZ DEFAULT now(),input TEXT,output TEXT,task TEXT,meta JSONB);
CREATE TABLE IF NOT EXISTS feedback(id BIGSERIAL PRIMARY KEY,interaction_id BIGINT REFERENCES interactions(id) ON DELETE CASCADE,rating INT CHECK (rating BETWEEN 1 AND 5),comment TEXT,labels TEXT[],ts TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS policies(key TEXT PRIMARY KEY,value JSONB,updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS kb(id BIGSERIAL PRIMARY KEY,source TEXT,chunk TEXT NOT NULL,emb vector(384),meta JSONB,created_at TIMESTAMPTZ DEFAULT now());
CREATE INDEX IF NOT EXISTS kb_emb_idx ON kb USING ivfflat (emb vector_cosine_ops) WITH (lists = 100);
INSERT INTO projects(name,status,progress) VALUES ('PAI-6 init','active',0.25) ON CONFLICT DO NOTHING;
